#------------------------------------------------------------------------------------------
# Hasta dc09.yml había DBT. En dc10.yml ya fue eliminado
#------------------------------------------------------------------------------------------
version: "3"                                    # Versión del docker compose. Hay algunas que ya no funcionan.
services:
    postgres:
      container_name: nga-postgres
      image: postgres:11                        # imagen:versión
      restart: always                           # Esto es para que restaure en caso de que el container falle.
      volumes:                                  # Importante: para la persistencia de datos. Carpeta donde quedarán. Todavía no sé cómo funciona.
        - nga-postgres-data:/var/lib/postgresql/data # Carpeta superset donde guarda por defecto los archivos.        
      environment:                              # Estas son las variables de entorno que va a usar éste contenedor
        POSTGRES_DB: nga-postgres
        POSTGRES_USER: nga-postgres
        POSTGRES_PASSWORD: nga-postgres
      ports:
        #- "5432:5432"                          # Puerto OS anfitrión : Puerto contenedor      
        - "5433:5432"                           # Puerto OS anfitrión : Puerto contenedor      
#------------------------------------------------------------------------------------------
    pgadmin:
      container_name: nga-pgadmin
      image: dpage/pgadmin4                     # imagen:versión
      environment:                              # Estas son las variables de entorno que va a usar éste contenedor
        PGADMIN_DEFAULT_EMAIL: "alexchavez1980@gmail.com"
        PGADMIN_DEFAULT_PASSWORD: "1234"
      ports:
        - "80:80"                               # Puerto OS anfitrión : Puerto contenedor              
      depends_on:
        - postgres
#------------------------------------------------------------------------------------------
    jupyter:
      container_name: nga-jupyter
      image: arjones/pyspark:2.4.5              # Chequear ésta versión. Depende qué queremos. Alternativa: jupyter/pyspark-notebook
      restart: always
      environment:
        - JUPYTER_TOKEN=1234
      volumes:                                  # Por ahora dejo comentados algunas carpetas. Hay sólo archivos de programas hechos por el profesor.
        #- nga-files:/nga-files
        - ./jupyter/notebook:/notebook
        #- nga-jupyter-data:./jupyter/notebook:/notebook
      ports:
        - "8888:8888"                           # PROBAR CON OTRO PUERTO O CON LA VERSION ALTERNATIVA DE LA IMAGEN      
#------------------------------------------------------------------------------------------
    superset:
      container_name: nga-superset
      image: amancevice/superset
      restart: always
      environment:
        MAPBOX_API_KEY: ${MAPBOX_API_KEY}
        SUPERSET_HOME: /etc/superset
      ports:
        - "8088:8088"
      volumes:
        - ./superset/conf/superset_config.py:/etc/superset/superset_config.py
        - nga-superset-data:/var/lib/superset   # Carpeta superset donde guarda por defecto los archivos. 
        #- nga-files:/nga-files       
#------------------------------------------------------------------------------------------
    postgres-airflow:
      container_name: postgres-airflow
      image: postgres:11
      restart: always
      volumes:
        - nga-postgres-airflow-data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: airflow
        POSTGRES_USER: airflow
        POSTGRES_PASSWORD: airflow
      ports:
        - "5434:5432"

    airflow:
      container_name: airflow
      image: puckel/docker-airflow
      restart: always
      depends_on:
        - postgres-airflow
      environment:
        EXECUTOR: Local
        AIRFLOW__CORE__LOAD_EXAMPLES: "false"
        AIRFLOW__WEBSERVER__WEB_SERVER_PORT: 9999 #9090
        AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres-airflow:5432/airflow
        AIRFLOW__CORE__FERNET_KEY: "Eff80poJxv6LE4432pDC6OmD6N449KCSuhUAMLXiq4U="
      ports:
        #- "9090:9090"
        - "9999:9999"
      volumes:
        - ./airflow/dags:/usr/local/airflow/dags
#------------------------------------------------------------------------------------------
volumes:                                        # Acá se definen los volúmenes o carpetas donde se guardan los archivos para la persistencia de datos.
  nga-postgres-data:
    driver: local
  nga-postgres-airflow-data:
    driver: local 
  nga-superset-data:
    driver: local 
#------------------------------------------------------------------------------------------
